[package]
name = "etwin_squirrel"
version = "0.8.0"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Manager for SQL schemas"
documentation = "https://github.com/eternal-twin/etwin"
homepage = "https://github.com/eternal-twin/etwin"
repository = "https://github.com/eternal-twin/etwin"
readme = "./README.md"
keywords = ["etwin"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
futures-util = "0.3.15"
include_dir = "0.6.1"
once_cell = "1.8.0"
petgraph = "0.6.0"
regex = "1.5.4"
serde = { version = "1.0.126", default-features = false, features = ["derive"] }
serde_json = "1.0.64"
sqlx = { version = "0.5.5", default-features = false, features = ["offline", "postgres", "runtime-tokio-rustls", "macros"] }
tokio = "1.8.1"
