[package]
name = "etwin_token_store"
version = "0.9.1"
authors = ["Charles Samborski <demurgos@demurgos.net>"]
description = "Token store implementation"
documentation = "https://github.com/eternal-twin/etwin"
homepage = "https://github.com/eternal-twin/etwin"
repository = "https://github.com/eternal-twin/etwin"
readme = "./README.md"
keywords = ["etwin"]
license = "AGPL-3.0-or-later"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
etwin_core = { version = "0.9.1", features = ["_serde", "sqlx"] }
etwin_db_schema = "0.9.1"
etwin_populate = "0.9.1"
neon = { version = "0.9.1", optional = true, default-features = false, features = ["napi-6"] }
regex = "1.5.4"
serde_json = "1.0.67"
sqlx = { version = "0.5.7", default-features = false, features = ["macros", "chrono", "offline", "postgres", "runtime-tokio-rustls", "uuid"] }

[dev-dependencies]
chrono = "0.4.19"
etwin_config = "0.9.1"
etwin_dinoparc_store = "0.9.1"
etwin_hammerfest_store = "0.9.1"
etwin_twinoid_store = "0.9.1"
serial_test = "0.5.1"
tokio = { version = "1.11.0", features = ["macros", "rt"] }
