[package]
name = "etwin_hammerfest_client"
version = "0.0.1"
authors = ["Moulins <arthur.heuillard@orange.fr>"]
description = "HammerfestClient implementations"
documentation = "https://github.com/eternal-twin/etwin"
homepage = "https://github.com/eternal-twin/etwin"
repository = "https://github.com/eternal-twin/etwin"
readme = "./README.md"
keywords = ["etwin"]
license = "AGPL-3.0-or-later"
edition = "2018"

[features]
default = ["http", "mem"]
http = ["reqwest", "scraper", "serde", "cssparser"]
mem = []

[dependencies]
async-trait = "^0.1.42"
cssparser = { version = "^0.27.2", optional = true }
chrono = "^0.4.19"
etwin_core = { path = "../core" }
neon = { version = "^0.7.0", optional = true, default-features = false, features = ["napi-runtime"] }
rand = "^0.8.0"
reqwest = { version = "^0.10.10", optional = true, features = ["cookies"] }
scraper = { version = "^0.12.0", optional = true }
serde = { version = "^1.0.115", optional = true, features = ["derive"] }
thiserror = "^1.0.23"
once_cell = "^1.5.2"

[dev-dependencies]
etwin_core = { path = "../core", features = ["serde"] }
serde_json = "^1.0.61"
